# version: "3"
services:
  nginx:
    # build:
    #   context: ./nginx
    image: skisscc/nginx:php83
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
    restart: always
    volumes:
      # nginx config
      - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./website/logs/nginx:/usr/local/nginx/logs
      # nginx vhosts config
      - ./website/http.d:/usr/local/nginx/conf.d
      # ssl
      - ./ssl:/ssl
      # php config
      - ./php83/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php83/www.conf:/usr/local/etc/php-fpm.conf:ro
      - ./website/logs/php83:/var/log/php
      # wwwroot
      - ./website/wwwroot:/wwwroot
    tmpfs:
      - /var/run/nginx-cache:rw,noexec,nosuid,size=512m
    networks:
      - default

  mysql:
    image: mysql/mysql-server:8.0.32-1.2.11-server
    # build:
    #   context: ./mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      # mysql config
      - ./mysql/entrypoint.sh:/entrypoint.sh
      - ./mysql/my.conf:/etc/my.cnf:ro
      - ./website/data:/var/lib/mysql/:rw
      - ./website/logs/mysql:/var/log/mysql:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_USER: "${MYSQL_ROOT_USER}"
      TZ: "$TZ"

  # memcached
#  memcached:
#    image: memcached:alpine
#    container_name: memcached
#    ports:
#      - "11211:11211"
#    environment:
#       MEMCACHED_CACHE_SIZE: "128"
#    networks:
#      - default

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 18.0.0.0/24